title: yanghaizhi's Blog
email: younghizhi@gmail.com


highlighter: rouge
markdown: kramdown
kramdown:
  input:         GFM
  auto_ids:      true
  auto_id_prefix: 'id-'

permalink: /:title

url:
baseurl:

redcarpet:
  extensions: [strikethrough, tables]

sass:
  sass_dir: public/css
  style: :compressed
